import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { requireAuth } from "../../../lib/auth";

// Example template generation logic
export function buildPromptTemplate() {
  // In a real application you might build this dynamically based on input.
  return {
    title: "Default Prompt",
    description: "A simple prompt template generated by the Next.js API.",
    variables: [
      { name: "userName", type: "string", example: "Alice" },
      { name: "goal", type: "string", example: "Write a short story" },
    ],
    template: "Hello {{userName}}, please help me {{goal}}."
  };
}

export async function GET(request: NextRequest) {
  // require the user to be signed in (returns a NextResponse when unauthorized)
  const auth = await requireAuth(request);
  if (auth instanceof NextResponse) {
    return auth; // 401 response already built
  }

  const template = buildPromptTemplate();
  return NextResponse.json(template);
}
